[aws] 
ec2-184-73-133-239.compute-1.amazonaws.com
ec2-54-147-188-32.compute-1.amazonaws.com
ec2-54-144-174-152.compute-1.amazonaws.com

[aws:vars] 
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/ec2-user/.ssh/id_rsa
